apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - persistence.yaml
  - configmap-mcp-patches.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
namespace: metamcp
