controllers:
  generic-device-plugin:
    type: daemonset
    containers:
      app:
        image:
          repository: ghcr.io/squat/generic-device-plugin
          tag: latest@sha256:ef5deb09dcf7e577c8603857ae56ef479d91be6ab6f40dd2427166d510b0745f
        args:
          - --log-level
          - info
          - --device=$(DEVICE_ZIGBEE)
          - --device=$(DEVICE_ZWAVE)
          - --device
          - |
            name: tun
            groups:
              - count: 1000
                paths:
                  - path: /dev/net/tun
          - --device
          - |
            name: dri
            groups:
              - count: 1000
                paths:
                  - path: /dev/dri
          - --device
          - |
            name: uinput
            groups:
              - count: 1000
                paths:
                  - path: /dev/uinput
          - --device
          - |
            name: uhid
            groups:
              - count: 1000
                paths:
                  - path: /dev/uhid
          - --device
          - |
            name: fuse
            groups:
              - count: 1000
                paths:
                  - path: /dev/fuse
        env:
          DEVICE_ZIGBEE: |-
            name: zigbee
            groups:
              - paths:
                  - path: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a499044e2813ec119a3321c7bd930c07-if00-port0
          DEVICE_ZWAVE: |-
            name: zwave
            groups:
              - paths:
                  - path: /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_86f2e3788a94eb11984f3a703d98b6d1-if00-port0
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
defaultPodOptions:
  priorityClassName: system-node-critical
persistence:
  dev:
    type: hostPath
    hostPath: /dev
    globalMounts:
      - readOnly: true
  sys:
    type: hostPath
    hostPath: /sys
    globalMounts:
      - readOnly: true
  var-lib-kubelet-device-plugins:
    type: hostPath
    hostPath: /var/lib/kubelet/device-plugins
