---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tsidp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tsidp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TS_AUTHKEY: "{{ .TS_AUTHKEY }}"
  dataFrom:
    - extract:
        key: tsidp
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tsidp-restic
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tsidp-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/tsidp"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-template
