---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-restic
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sabnzbd-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .REPOSITORY_TEMPLATE }}/sabnzbd"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: sabnzbd-rdst
  resources:
    requests:
      storage: 2Gi
  storageClassName: ceph-rbd
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: sabnzbd-rdst
spec:
  trigger:
    manual: restore-once-3
  restic:
    repository: sabnzbd-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: ceph-rbd
    cacheStorageClassName: ceph-rbd
    volumeSnapshotClassName: ceph-rbd-snapshot
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    capacity: 2Gi # must match the PersistentVolumeClaim `.resources.requests.storage` size above
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sabnzbd-rsrc
spec:
  sourcePVC: sabnzbd
  trigger:
    schedule: "15 */8 * * *"
  restic:
    pruneIntervalDays: 7
    repository: sabnzbd-restic-secret
    copyMethod: Snapshot
    accessModes: ["ReadWriteOnce"]
    storageClassName: ceph-rbd
    cacheStorageClassName: ceph-rbd
    volumeSnapshotClassName: ceph-rbd-snapshot
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 24
      daily: 7
      weekly: 5